### ISSUE TITLE
Idea: Large Screen UI

### ISSUE THREAD

**Issue by cdmwebs** [bus-detective/web-client#2]
I was using Bus Detective on my iPad and desktop where there's a lot more real estate. I poked around a bit and came up with this.

![screen shot 2015-09-14 at 8 44 12 pm](https://cloud.githubusercontent.com/assets/2399/9865242/8bbe1dc6-5b21-11e5-9c27-ad09154a0bcc.png)

Thoughts?

**Comment by cdmwebs** [comment]
Here's a second version with the search box collapsed in to the results column.

![screen shot 2015-09-14 at 8 50 01 pm](https://cloud.githubusercontent.com/assets/2399/9865306/3eb9ec52-5b22-11e5-9854-9fba1f8b1de5.png)

**Comment by joelturnbull** [comment]
Looks good. I prefer version 2. I would remove the "Search Results" label
